version: '3'
services:
  app-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: 'app/app-service'
    container_name: 'app-service.test'
    ports:
      - '${APP_PORT:-8070}:80'
    volumes:
      - ./:/var/www/html
    depends_on:
      - app-service-mysql
  app-service-mysql:
    platform: linux/x86_64
    image: 'mysql:5.7'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'app-service-volume:/var/lib/mysql'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
  phpmyadmin-service:
    image: phpmyadmin
    ports:
      - '${PHP_MY_ADMIN_PORT}:80'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      PMA_HOST: '${DB_HOST}'
      PMA_USER: '${DB_USERNAME}'
      PMA_PASSWORD: '${DB_PASSWORD}'
    depends_on:
      - app-service-mysql
networks:
  default:
    external:
      name: app-network
volumes:
  app-service-volume:
    driver: local